### ISSUE TITLE
While clicking on a top level, map is zooming

### ISSUE THREAD

**Issue by Falke-Design** [ignaciofagian/L.LayerTreeControl#1]
You can prevent zooming with `L.DomEvent.disableClickPropagation(elem)`
![zoom-in-tree-control](https://user-images.githubusercontent.com/19800037/193298743-6de01851-6a07-49cb-8c1f-d9ac7e72b739.gif)

**Comment by ignaciofagian** [comment]
thanks for your feedback, I appreciate it
