### ISSUE TITLE
Preview order of layers

### ISSUE THREAD

**Issue by qaniqani** [ignaciofagian/L.LayerTreeControl#3]
Hi, nice work..

It would be nice to be able to change the display order of dynamically loaded and marked layers. Optionally, changing the order will be an option.

Thnx.

**Comment by ignaciofagian** [comment]
Hi! 
yes I agree with you, it's an interesting feature. Now I'm planning to do some testing but I will develop this. 
Thanks for the idea

**Comment by qaniqani** [comment]
I wiss you success..
